### ISSUE TITLE
Question on deep sorting/filtering

### ISSUE THREAD

**Issue by cope** [GraphQLGuide/all-the-databases#1]
Hi,

Would it be possible to sort/filter on nested data where the nested data comes from a different database?

For example, lets say we want to sort/filter the publicFeed based on the authors. For example sort the publicFeed by `author.firstname` of filter by `author.firstname = Elissa` and so on.

Would this be possible?

**Comment by lorensr** [comment]
> Would it be possible to sort/filter on nested data where the nested data comes from a different database?

I don't think there's an efficient way. I would store the relevant data in the same db.

**Comment by cope** [comment]
Ok. Thanks.
